

# Install latest dependencies with
#   conda create -n gui -f gui-base.yml
#
# But we usually create a lockfile from this file:
#   conda-lock --file gui-base.yml --lockfile gui-lock.yml
#
name: gui
channels:
  - conda-forge
dependencies:
  - pip:
    - gpytorch
    - botorch
    - lume-model
    - pandas
    - pymongo
    - pyyaml


