name: synapse-ml

channels:
  - conda-forge
  - nvidia
  - nodefaults
  - pytorch

dependencies:
  - botorch
  - gpytorch
  - lume-model>=2.0.1
  - mlflow
  - pandas
  - pip
  - pymongo
  - python
  - pytorch
  - pytorch-cuda=12.4  # [linux]
  - pyyaml
