name: ml-training

channels:
  - conda-forge
#  - nvidia
  - nodefaults

dependencies:
  - botorch
#  - cuda-version=12.4  # for Perlmutter (NERSC)
  - gpytorch
  - pandas
  - pip
  - python
#  - pytorch-gpu
  - pymongo
  - pyyaml
  - lume-model
