name: synapse-ml

channels:
  - conda-forge
  - nvidia
  - nodefaults

dependencies:
  - botorch
  - cuda-version=12.4  # for Perlmutter (NERSC)
  - gpytorch
  - lume-model>=2.0.1
  - pandas
  - pip
  - pymongo
  - python
  - pytorch-gpu
  - pyyaml
